// Generated by CoffeeScript 1.6.3
(function() {
  var Graph,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Graph = (function() {
    function Graph(edges) {
      var edge, vertices;
      this.edges = edges;
      vertices = ((function() {
        var _i, _len, _ref, _results;
        if (_ref = edge[0], __indexOf.call(vertices, _ref) < 0) {
          _results = [];
          for (_i = 0, _len = edges.length; _i < _len; _i++) {
            edge = edges[_i];
            _results.push(edge[0]);
          }
          return _results;
        }
      })());
    }

    return Graph;

  })();

}).call(this);
